name: Factions
version: '${version}'
main: dev.tieseler.factions.Factions
api-version: '1.20'
load: STARTUP
folia-supported: true

softdepend:
  - PlaceholderAPI

commands:
  chunk:
    description: Get information about a chunk
    permission: factions.chunks
  peposit:
    description: Setz dich doch ein wenig :)
    usage: /<command>
    permission: factions.peposit
    permission-message: Nö, du musst stehen bleiben
    aliases:
      - sit
  faction:
    description: Mit diesem Befehl verwaltest du deine Faction
    permission: factions.faction
    aliases:
      - f
  invite:
    description: Lade einen Spieler in deine Faction ein
    permission: factions.invite
    usage: /invite <Spieler> | <accept> | <deny>
    aliases:
      - i